title: Johnny Starr's Blog
email: johnnystarr@gmail.com
description: >-
  Stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  johnnystarr
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-feed

# theme specific stuff
plainwhite:
  name: Johnny Starr
  tagline: Sr. DevOps Engineer, Technologist, Nerd.
  date_format: "%b %-d, %Y"
  portfolio_image:  "assets/johnny.jpg"
  dark_mode: false
  sitemap: true
  show_excerpts: true
  analytics_id: "G-6345ETHHQC"

  navigation:
    - title: About
      url: "/about"
    - title: Projects
      url: "/projects"
    - title: Resume
      url: "/resume"

  social_links:
    github: johnnystarr
    linkedIn: in/johnny-starr-40783372 # format: locale/username
    twitter: johnnystarrwork